# Use the official Nginx image
FROM nginx:alpine

# Copy the contents of the frontend folder to the Nginx HTML directory
COPY frontend /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
